[package]
name = "factorial"
version = "0.1.0"
authors = ["Tyler Park <tyler.park@fortemtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.2.1"
rustop = "1.1.1"